config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope "(:locale)", locale: /es|de/ do

    resources :projects, only: [:index, :create, :new, :show] do
      resources :applications, only: [:new, :create]
    end

    get 'applications/:application_id/confirmation', to: 'applications#confirmation', as: :application_confirmation

    root to: 'pages#home'
    get 'ngos/home', to: 'ngos#home', as: :ngos_home
    get 'about-vamos', to: 'pages#about_vamos', as: :about_vamos
    get 'location', to: 'pages#filter_location', as: :filter_location
    get 'interests', to: 'pages#filter_interests', as: :filter_interests
    get 'timeframe', to: 'pages#filter_timeframe', as: :filter_timeframe
    get "dashboard", to: "users#dashboard", as: :user_dashboard
    get 'time', to: 'pages#filter_time', as: :filter_time
    get 'users/profile', to: 'users#profile', as: :user_profile
    get 'privacy-policy-vamos', to: 'pages#privacy_policy_vamos', as: :privacy_policy_vamos

    resources :conversations, only: [:index, :show, :create] do
      resources :messages, only: [:create]
    end

    get 'sitemap', to: 'sitemap#index', defaults: { format: "xml" }

    resources :teams, only: [:new, :create]

    get 'users/projects', to: 'users#projects', as: :user_projects #last modification

    resources :ngos, only: [:new, :create]

    resources :applications, only: [:index, :show] do
      resources :reviews, only: [:new, :create]
    end

    resources :applications, only: [] do
      member do
        patch "/accept_applications", to: "applications#accept_applications", as: :accept_applications
        patch "/reject_applications", to: "applications#reject_applications", as: :reject_applications
        patch "/accept_conversation", to: "applications#accept_conversation", as: :accept_conversation
        patch "/reject_conversation", to: "applications#reject_conversation", as: :reject_conversation
      end
    end

  end













  # needed for modal login

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :project
  belongs_to :team
  has_many :reviews
  has_one :conversation

  validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :set_locale
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

helper_method :resource_name, :resource, :devise_mapping, :resource_class
def resource_name
  :user
end

def set_locale(&action)
  locale = params[:locale] || I18n.default_locale
  I18n.with_locale(locale, &action)
end

def default_url_options
  { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
end

def resource
  @resource ||= User.new
end

def resource_class
  User
end

def devise_mapping
  @devise_mapping ||= Devise.mappings[:user]
end

protected # can be called by any instance of the same controller (not only inside the class!)
# needed for the invitation form (permitting the params for when a new member accepts an invitation
# and registers.)

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:accept_invitation, keys: [:first_name, :last_name, :description, :phone, :photo])
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :description, :phone])
end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @project = Project.find(params[:project_id])
    @teams = current_user.teams
    @application = Application.new
  end

  def create
    @application = Application.new(application_params)
    @application.status = "pending"
    @project = Project.find(params[:project_id])
    @application.project = @project
    @team = Team.find(params[:application][:team_id])
    @application.team = @team

    if @application.save
      @conversation = Conversation.create(application: @application)
      @message = Message.new(message_params)
      @message.conversation = @conversation
      @message.user = current_user
      @message.save
      # create a new message from the form to start the conversation
      redirect_to application_confirmation_path(@application) #the button for team-creation and for Contacting the NGO now is the same.
    else
      render :new
    end
  end

   def index
    @user = current_user
    @ngo_applications = current_user.ngo_applications
    @applications = current_user.applications.order(created_at: :asc)
  end

  def show
    @application = Application.find(params[:id])
    @team = @application.team
  end


  def confirmation
    @application = Application.find(params[:application_id])
  end

  def accept_applications
    @application = Application.find(params[:id])
    @application.status = "accepted"
    @application.save
    redirect_to applications_path
  end

  def reject_applications
    @application = Application.find(params[:id])
    @application.status = "rejected"
    @application.save
    redirect_to applications_path
  end

  def accept_conversation
    @application = Application.find(params[:id])
    @application.status = "accepted"
    @application.save
    @conversation = @application.conversation
    redirect_to conversation_path(@conversation)
  end

  def reject_conversation
    @application = Application.find(params[:id])
    @application.status = "rejected"
    @application.save
    @conversation = @application.conversation
    redirect_to conversation_path(@conversation)
  end

  private

  def application_params
    params.require(:application).permit(:team_id, :start_date, :end_date, :start_time, :end_time)
  end

  def message_params
    params.require(:application).require(:message).permit(:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/_team_membership_fields.html.erb
<div class="nested-fields">
  <%= f.input :user, label: false, placeholder: "example@gmail.com" %>
</div>

app/views/applications/confirmation.html.erb
<div class="progress-bar-container progress-bar-container-step-3">
  <div class="progress-bar-area">
    <div class="progress" id="steps-progress">
      <div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <div class="progress-step first-step text-center">
      <p><%= t(".step_1") %></p>
      <i class="fas fa-circle progress-icon" style="position:absolute;color:white;"></i>
      <i class="fas fa-check-circle progress-icon" style="position:relative;bottom:0px;left:0px;"></i>
    </div>
    <div class="progress-step second-step text-center">
      <p><%= t(".step_2") %></p>
      <i class="fas fa-circle progress-icon" style="position:absolute;color:white;"></i>
      <i class="fas fa-check-circle progress-icon" style="position:relative;bottom:0px;left:0px;"></i>
    </div>
    <div class="progress-step third-step text-center">
      <p><%= t(".step_3") %></p>
      <i class="fas fa-circle progress-icon" style="position:absolute;color:white;"></i>
      <i class="far fa-circle progress-icon" style="position:relative;bottom:0px;left:0px;"></i>
    </div>
  </div>
</div>


<div class="application-confirmation-container">
  <%= render 'shared/mobile_navbar' %>
  <div class="confirmation-message pt-3">
    <% if @application.team.users.any? {|user| user.first_name == nil} %>
      <h2 class="text-center mb-4 mt-3"><%= t(".team_name_for_html", name: @application.team.name) %></h2>
      <p><%= t(".info_text_for_html") %></p>
    <% else %>
      <h2 class="text-center"><span class="orange"><%= @application.team.name %></span><%= t(".application_sent_text") %></h2>
    <% end %>

  </div>
  <div>
    <h3 class="mt-5 mb-3"><%= @application.project.title %> <%= t(".with") %> <%= @application.project.ngo.name %></h3>
  </div>
  <div class="confirmation-picture mb-5">
    <%= cl_image_tag @application.project.photos.first.key %>
  </div>

  <% if @application.team.users.any? {|user| user.first_name == nil} == false %>
    <div class="d-flex justify-content-between mt-1">
      <%= cl_image_tag @application.project.ngo.user.photo.key, class: "contact-avatar" %>
      <div class="ml-3">

        <h3><%= @application.project.ngo.user.first_name %> <%= t(".your_contact_text") %> <%= @application.project.ngo.name %> </h3>
        <h3 class="m-0"><%= t(".question") %></h3>
      </div>
      <div class="button hide-mobile"> <!-- done -->

        <%= link_to conversation_path(@application.conversation) do  %>
          <h3 class="enter-chat-button">
            <%= t(".send_message") %>
          </h3>
        <% end %>
      </div>
    </div>

    <div class="button-1 hide-desktop">
      <%= link_to conversation_path(@application.conversation) do  %>
        <h3 class="enter-chat-button-mobile">
          <%= t(".send_message") %>
        </h3>
      <% end %>
    </div>
    <div class="button go-back mt-2">
      <%= link_to projects_path do  %>
        <h3 class="opportunities-chat-button">
          <%= t('.more_opportunities') %>
        </h3>
      <% end %>
    </div>
  <% else %>
    <div class="d-flex justify-content-between mt-3">
      <%= cl_image_tag @application.project.ngo.user.photo.key, class: "contact-avatar" %>
      <div class="ml-3">
        <h3><%= @application.project.ngo.user.first_name %> <%= t(".your_contact_text") %> <%= @application.project.ngo.name %> </h3>
        <h3 class="m-0"><%= t(".question") %></h3>
      </div>
      <div class="button go-back">
        <%= link_to projects_path do  %>
          <h3 class="opportunities-chat-button">
            <%= t('.more_opportunities') %>
          </h3>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/applications/index.html.erb
<div class="has-navbar-so-margin">
<%= render 'shared/mobile_navbar' %>
  <div class="content-container">
<!-- desktop version of application-->
    <div class="content-container-ngo-applications-desktop hide-mobile mb-5">
      <div class="container ngo-application-datas mb-5 mt-5 hide-mobile">
        <div class="row table-titles border-bottom">
          <div class="col-2">
            <h4 class="status-table"><%= t(".status") %></h4>

          </div>
          <div class="col-3">
            <h4 class="project-name-table"><%= t(".project_name") %></h4>
          </div>
          <div class="col-2">
            <h4 class="team-name-table"><%= t(".team_name") %></h4>
          </div>
          <div class="col-1">
            <h4 class="date-table"><%= t(".date") %></h4>
          </div>
          <div class="col-1">
            <h4 class="houre-table"><%= t(".hours") %></h4>
          </div>
          <div class="col-2">
            <h4 class="date-table"><%= t(".application_date") %></h4>
          </div>
        </div>
        <% @ngo_applications.each do |application| %>
          <div class="row border-bottom my-4 pb-3">
            <div class="application-result col-2">
              <div class="application-status-app-desktop">
              <% if application.status == "pending" %>
                <div class="accept-button-app-desktop px-3 mb-2">
                  <%= link_to t(".accept"), accept_applications_application_path(application), method: :patch, class: "green-color"%>
                </div>
                <div class="reject-button-app-desktop px-3 mb-2">
                  <%= link_to t(".reject"), reject_applications_application_path(application), method: :patch, class: "red-color"%>
                </div>
              <% elsif application.status == "accepted" %>
                <h4 class="accepted-text"><%= t(".accepted") %> <i class="fas fa-check"></i></h4>
              <% elsif application.status == "rejected" %>
                <h4 class="rejected-text"><%= t(".rejected") %> <i class="fas fa-times"></i> </h4>
              <% end %>
              </div>
            </div>
            <div class="col-3">
               <h4 class="project-name-application"><%= application.project.title %></h4>
            </div>
            <div class="number col-2">
              <h4 class="m-0 team-name-ngo"><%= application.team.name %></h4>
              <% link_to teams_path(application.team) %>
              <h4 style="color:#f28b3c"> <%= application.team.users.count %> people</h4>
              </a>
            </div>
            <div class="col-1">
              <h4 class="date-application"><%= application.project.start_date.strftime("%d %B") %> </h4>
            </div>
            <div class="col-1">
              <h4 class="numb-hour"><%= (application.project.end_time - application.project.start_time) %> hours</h4>
            </div>
            <div class="col-2">
              <h4 class="numb-application"><%= application.created_at.strftime("%d %B") %></h4>
            </div>
            <div class="col-1">
              <%= link_to t(".details"), application_path(application.id), class: "button-details w-20 mt-3" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>  <!-- don't touch end -->
            <!-- mobile version of application-->
    <div class="ngo-applications-mobile hide-desktop">
      <div class="title-mobile my-4 py-1">
        Applications
      </div>
      <% @ngo_applications.each do |application| %>
        <div class="ngo-application d-flex my-4 py-1 border-bottom">
          <div class="application-name-team">
            <h3 class="project-style"><%= application.project.title %></h3>
            <div class="team-info">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <div class="line-1 d-flex mY-4 pb-0">
                    <p class="date-style"><%= application.project.start_date.strftime("%d/%m ") %>·  </p>
                    <pre> </pre>
                    <p class="numb-style"> <%= application.team.users.count %> people · </p>
                    <pre> </pre>
                    <p class="hour-style"> <%= (application.project.end_time - application.project.start_time) %> hours</p>
                  </div>
                  <div class="line-3 d-flex mb-6 mt-3">
                    <% application.team.users.each do |user| %>
                      <div class= "pic"> <%= cl_image_tag user.photo.key, width: 30, height: 30, class: "rounded-circle" %>
                      </div>
                    <% end %>
                  </div>
                  <p class="m-0 team-name-ngo"><%= application.team.name %></p>
                </div>
              </div>
            </div>
          </div>

          <div class="application-status mr-2">
            <% if application.status == "pending" %>
              <div class="accept-button px-3 my-2">
                <%= link_to t(".accept"), accept_applications_application_path(application), method: :patch, class: "green-color"%>
              </div>
              <div class="reject-button px-3 my-2">
                <%= link_to t(".reject"), reject_applications_application_path(application), method: :patch, class: "red-color"%>
              </div>
            <% elsif application.status == "accepted" %>
              <p class="accepted-text"> <%= t(".accepted") %> <i class="fas fa-check"></i></p>
            <% elsif application.status == "rejected" %>
              <p class="rejected-text"><%= t(".rejected") %> <i class="fas fa-times"></i></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/applications/new.html.erb
<div class="progress-bar-container progress-bar-container-step-2">
  <div class="progress-bar-area">
    <div class="progress" id="steps-progress">
      <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <div class="progress-step first-step text-center">
      <p><%= t(".step_1") %></p>
      <i class="fas fa-circle progress-icon" style="position:absolute;color:white;"></i>
      <i class="fas fa-check-circle progress-icon" style="position:relative;bottom:0px;left:0px;"></i>
    </div>
    <div class="progress-step second-step text-center">
      <p><%= t(".step_2") %></p>
      <i class="fas fa-circle progress-icon" style="position:absolute;color:white;"></i>
      <i class="far fa-circle progress-icon" style="position:relative;bottom:0px;left:0px;"></i>
    </div>
    <div class="progress-step third-step text-center">
      <p><%= t(".step_3") %></p>
      <i class="fas fa-circle progress-icon"></i>
    </div>
  </div>
</div>

<div class="content-container-application-new">
  <div class="principal-div d-flex justify-content-between">
    <div class="form-style-desktop">
      <h3><strong><%= t(".project") %>:</strong> <%= @project.title %></h3>
      <h3><strong><%= t(".organization") %>:</strong> <%= @project.ngo.name %></h3>

      <div class="form-group simple-form">
        <%= simple_form_for ([@project, @application])  do |f| %>
          <h3 class="mt-4"><%= t(".selected_team") %></h3>
          <div class="mb-2">
            <%= f.association :team, label: false, input_html: {class: " form-control mt-2"}, collection: current_user.teams, selected: current_user.teams.last%>
          </div>

          <div class="mb-4">
            <h3><%= t(".application_message") %></h3>
            <%= f.simple_fields_for :message do |message_fields| %>
              <%= message_fields.input :body, required: true, as: :text, placeholder: t(".motivation"), label: false, input_html: {rows: 5} %>
            <% end %>
          </div>

          <%= f.submit t(".send_application"), class: "button-vamos primary-style w-100 mt-0"%>
        <% end %>
      </div>

      <%= form_tag(new_team_path, :method => "get") do %>
        <%= hidden_field_tag(:id, params[:project_id]) %>
        <%= button_tag :type => "submit", :class => "border-0 mb-5" do %>
          <%= t(".apply") %><i class="mt-2 far fa-arrow-alt-circle-right orange ml-2"></i>
        <% end %>
      <% end %>
    </div>

    <div class="picture-style-desktop">
      <div class="text-center-desktop">
        <%= cl_image_tag @project.photos.first.key, id: "team-image-desktop" %>
      </div>
    </div>
  </div>
</div>

app/views/applications/show.html.erb
<div class="content-container-application-show mt-5">
  <h1><%= t(".application_overview") %> "<span class="orange"><%= @application.project.title %></span>"</h1>
  <h2 class= "mt-5"><%= @team.name %></h2>

  <div class="d-flex justify-content-around mt-5">
    <% @team.users.each do |user| %>

    <div class= "text-center mb-3 mr-5">
      <div class="mb-2">
        <%= cl_image_tag user.photo.key, width: 60, height: 60, class: "avatar-x-large" %>
      </div>

      <div class="name-width">
        <div>
        <%= user.first_name %>
        </div>

        <div>
          <%= user.last_name %>
        </div>
      </div>

    </div>
    <% end %>

    <div>
      <div class="speech-bubble">
        <p> <%= @application.conversation.messages.first.body %></p>
      </div>
      <div class="mt-4">
        <%= link_to t(".send_message"), conversation_path(@application.conversation), class: "message-button"%>
      </div>
    </div>

    <div class="application-status-app-desktop ml-5">
      <% if @application.status == "pending" %>
        <div class="accept-button-app-desktop px-3 mb-2">
          <%= link_to t(".accept"), accept_applications_application_path(@application), method: :patch, class: "green-color"%>
        </div>
        <div class="reject-button-app-desktop px-3 mb-2">
          <%= link_to t(".reject"), reject_applications_application_path(@application), method: :patch, class: "red-color"%>
        </div>
      <% elsif @application.status == "accepted" %>
        <h4 class="accepted-text"><%= t(".accepted") %> <i class="fas fa-check"></i> </h4>
      <% elsif @application.status == "rejected" %>
        <h4 class="rejected-text"><%= t(".rejected") %> <i class="fas fa-times"></i> </h4>
      <% end %>
    </div>

  </div>
</div>