config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope "(:locale)", locale: /es|de/ do

    resources :projects, only: [:index, :create, :new, :show] do
      resources :applications, only: [:new, :create]
    end

    get 'applications/:application_id/confirmation', to: 'applications#confirmation', as: :application_confirmation

    root to: 'pages#home'
    get 'ngos/home', to: 'ngos#home', as: :ngos_home
    get 'about-vamos', to: 'pages#about_vamos', as: :about_vamos
    get 'location', to: 'pages#filter_location', as: :filter_location
    get 'interests', to: 'pages#filter_interests', as: :filter_interests
    get 'timeframe', to: 'pages#filter_timeframe', as: :filter_timeframe
    get "dashboard", to: "users#dashboard", as: :user_dashboard
    get 'time', to: 'pages#filter_time', as: :filter_time
    get 'users/profile', to: 'users#profile', as: :user_profile
    get 'privacy-policy-vamos', to: 'pages#privacy_policy_vamos', as: :privacy_policy_vamos

    resources :conversations, only: [:index, :show, :create] do
      resources :messages, only: [:create]
    end

    get 'sitemap', to: 'sitemap#index', defaults: { format: "xml" }

    resources :teams, only: [:new, :create]

    get 'users/projects', to: 'users#projects', as: :user_projects #last modification

    resources :ngos, only: [:new, :create]

    resources :applications, only: [:index, :show] do
      resources :reviews, only: [:new, :create]
    end

    resources :applications, only: [] do
      member do
        patch "/accept_applications", to: "applications#accept_applications", as: :accept_applications
        patch "/reject_applications", to: "applications#reject_applications", as: :reject_applications
        patch "/accept_conversation", to: "applications#accept_conversation", as: :accept_conversation
        patch "/reject_conversation", to: "applications#reject_conversation", as: :reject_conversation
      end
    end

  end













  # needed for modal login

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  after_create :set_default_avatar
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :invitable, invite_for: 0
        # devise invitable comes from new gem and allows as to invite users.

  # Devise omniauthable makes user facebook omiauthable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :reviews
  has_one :ngo
  has_many :ngo_reviews, through: :ngo, source: :reviews
  has_many :team_memberships
  has_many :teams, through: :team_memberships
  has_many :applications, through: :teams
  has_many :ngo_applications, through: :ngo, source: :applications

  has_many :ngo_conversations, through: :ngo_applications, source: :conversation
  has_many :team_conversations, through: :applications, source: :conversation

  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }, presence: true, uniqueness: true

  attr_accessor :current_password

  def ngo_manager?
    ngo.present?
  end

  require 'open-uri'

  def set_default_avatar
    if self.photo.attached? == false
      self.photo.attach(io: File.open("app/assets/images/missing_avatar.png"), filename: 'missing_avatar.png', content_type: 'image/png')
    end
  end

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice("provider", "uid")
    user_params.merge! auth.info.slice("email", "first_name", "last_name")
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :html, :js
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  respond_to :html, :js
  # before_action :configure_sign_in_params, only: [:create]



  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @applications = current_user.applications.order(created_at: :asc)
  end

  def profile
    @user = current_user
    @ngo_applications = current_user.ngo_applications
    @ngo_reviews = current_user.ngo_reviews
  end

  def projects
    @user = current_user
    @ngo_projects = current_user.ngo.projects
    # @projects = current_user.projects.order(created_at: :asc)
  end

end

app/views/users/application.html.erb
<div class="has-navbar-so-margin">
<%= render 'shared/mobile_navbar' %>
  <div class="content-container">
<!-- desktop version of application-->
    <div class="content-container-ngo-bookings-desktop hide-mobile mb-5">
      <div class="container ngo-booking-datas mb-5 mt-5 hide-mobile">
        <div class="row table-titles border-bottom">
          <div class="col-2">
            <h4 class="status-table">Status</h4>
          </div>
          <div class="col-3">
            <h4 class="project-name-table">Project Name</h4>
          </div>
          <div class="col-2">
            <h4 class="team-name-table">Team Name</h4>
          </div>
          <div class="col-1">
            <h4 class="date-table">Starting date</h4>
          </div>
          <div class="col-1">
            <h4 class="houre-table">Hour</h4>
          </div>
          <div class="col-2">
            <h4 class="date-table">Booked date</h4>
          </div>
        </div>
        <% @ngo_bookings.each do |booking| %>
          <div class="row border-bottom my-4 pb-3">
            <div class="booking-result col-2">
              <div class="booking-status-app-desktop">
              <% if booking.status == "pending" %>
                <div class="accept-button-app-desktop px-3 mb-2">
                  <%= link_to "Accept", accept_booking_path(booking), method: :patch, class: "green-color"%>
                </div>
                <div class="reject-button-app-desktop px-3 mb-2">
                  <%= link_to "Reject", reject_booking_path(booking), method: :patch, class: "red-color"%>
                </div>
              <% elsif booking.status == "accepted" %>
                <h4 id="accepted-text-m">Accepted</h4>
              <% elsif booking.status == "rejected" %>
                <h4 id="rejected-text-m">Declined</h4>
              <% end %>
              </div>
            </div>
            <div class="col-3">
               <h4 class="project-name-booking"><%= booking.project.title %></h4>
            </div>
            <div class="number col-2">
              <h4 class="m-0 team-name-ngo"><%= booking.team.name %></h4>
              <% link_to teams_path(booking.team) %>
              <h4 style="color:#f28b3c"> <%= booking.team.users.count %> people</h4>
              </a>
            </div>
            <div class="col-1">
              <h4 class="date-application"><%= booking.project.start_date.strftime("%d %B") %> </h4>
            </div>
            <div class="col-1">
              <h4 class="numb-hour"><%= (booking.project.end_time - booking.project.start_time) %> hours</h4>
            </div>
            <div class="col-2">
              <h4 class="numb-booking"><%= booking.created_at.strftime("%d %B") %></h4>
            </div>
            <div class="col-1">
              <%= link_to "Details", filter_location_path, class: "button-details w-20 mt-3" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>  <!-- don't touch end -->
            <!-- mobile version of application-->
    <div class="ngo-bookings-mobile hide-desktop">
      <div class="title-mobile my-4 py-1">
        Applications
      </div>
      <% @ngo_bookings.each do |booking| %>
        <div class="ngo-booking d-flex my-4 py-1 border-bottom">
          <div class="booking-name-team">
            <h3 class="project-style"><%= booking.project.title %></h3>
            <div class="team-info">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <div class="line-1 d-flex mY-4 pb-0">
                    <p class="date-style"><%= booking.project.start_date.strftime("%d/%m ") %>·  </p>
                    <pre> </pre>
                    <p class="numb-style"> <%= booking.team.users.count %> people · </p>
                    <pre> </pre>
                    <p class="hour-style"> <%= (booking.project.end_time - booking.project.start_time) %> hours</p>
                  </div>
                  <div class="line-3 d-flex mb-6 mt-3">
                    <% booking.team.users.each do |user| %>
                      <div class= "pic"> <%= cl_image_tag user.photo.key, width: 30, height: 30, class: "rounded-circle" %>
                      </div>
                    <% end %>
                    <div class= "arrow">
                      <i class="fas fa-chevron-right"></i>
                      <%= link_to "Accept", accept_booking_path(booking), method: :patch, class: "green-color"%>
                    </div>
                  </div>
                  <p class="m-0 team-name-ngo"><%= booking.team.name %></p>
                </div>
              </div>
            </div>
          </div>

          <div class="booking-status mr-2">
            <% if booking.status == "pending" %>
              <div class="accept-button px-3 my-2">
                <%= link_to "Accept", accept_booking_path(booking), method: :patch, class: "green-color"%>
              </div>
              <div class="reject-button px-3 my-2">
                <%= link_to "Reject", reject_booking_path(booking), method: :patch, class: "red-color"%>
              </div>
            <% elsif booking.status == "accepted" %>
              <p id="accepted-text">Accepted</p>
            <% elsif booking.status == "rejected" %>
              <p style="font-size: 18px">Declined</p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/applications.html.erb
<div class="has-navbar-so-margin">
<%= render 'shared/mobile_navbar' %>
  <div class="content-container">
<!-- desktop version of application-->
    <div class="content-container-ngo-applications-desktop hide-mobile mb-5">
      <div class="container ngo-application-datas mb-5 mt-5 hide-mobile">
        <div class="row table-titles border-bottom">
          <div class="col-2">
            <h4 class="status-table"><%= t(".status") %></h4>

          </div>
          <div class="col-3">
            <h4 class="project-name-table"><%= t(".project_name") %></h4>
          </div>
          <div class="col-2">
            <h4 class="team-name-table"><%= t(".team_name") %></h4>
          </div>
          <div class="col-1">
            <h4 class="date-table"><%= t(".date") %></h4>
          </div>
          <div class="col-1">
            <h4 class="houre-table"><%= t(".hours") %></h4>
          </div>
          <div class="col-2">
            <h4 class="date-table"><%= t(".application_date") %></h4>
          </div>
        </div>
        <% @ngo_applications.each do |application| %>
          <div class="row border-bottom my-4 pb-3">
            <div class="application-result col-2">
              <div class="application-status-app-desktop">
              <% if application.status == "pending" %>
                <div class="accept-button-app-desktop px-3 mb-2">
                  <%= link_to "Accept", accept_application_path(application), method: :patch, class: "green-color"%>
                </div>
                <div class="reject-button-app-desktop px-3 mb-2">
                  <%= link_to "Reject", reject_application_path(application), method: :patch, class: "red-color"%>
                </div>
              <% elsif application.status == "accepted" %>
                <h4 id="accepted-text-m">Accepted</h4>
              <% elsif application.status == "rejected" %>
                <h4 id="rejected-text-m">Declined</h4>
              <% end %>
              </div>
            </div>
            <div class="col-3">
               <h4 class="project-name-application"><%= application.project.title %></h4>
            </div>
            <div class="number col-2">
              <h4 class="m-0 team-name-ngo"><%= application.team.name %></h4>
              <% link_to teams_path(application.team) %>
              <h4 style="color:#f28b3c"> <%= application.team.users.count %> people</h4>
              </a>
            </div>
            <div class="col-1">
              <h4 class="date-application"><%= application.project.start_date.strftime("%d %B") %> </h4>
            </div>
            <div class="col-1">
              <h4 class="numb-hour"><%= (application.project.end_time - application.project.start_time) %> hours</h4>
            </div>
            <div class="col-2">
              <h4 class="numb-application"><%= application.created_at.strftime("%d %B") %></h4>
            </div>
            <div class="col-1">

              <%= link_to "Details", project_application_path(application.project.id), class: "button-details w-20 mt-3" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>  <!-- don't touch end -->
            <!-- mobile version of application-->
    <div class="ngo-applications-mobile hide-desktop">
      <div class="title-mobile my-4 py-1">
        Applications
      </div>
      <% @ngo_applications.each do |application| %>
        <div class="ngo-application d-flex my-4 py-1 border-bottom">
          <div class="application-name-team">
            <h3 class="project-style"><%= application.project.title %></h3>
            <div class="team-info">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <div class="line-1 d-flex mY-4 pb-0">
                    <p class="date-style"><%= application.project.start_date.strftime("%d/%m ") %>·  </p>
                    <pre> </pre>
                    <p class="numb-style"> <%= application.team.users.count %> people · </p>
                    <pre> </pre>
                    <p class="hour-style"> <%= (application.project.end_time - application.project.start_time) %> hours</p>
                  </div>
                  <div class="line-3 d-flex mb-6 mt-3">
                    <% application.team.users.each do |user| %>
                      <div class= "pic"> <%= cl_image_tag user.photo.key, width: 30, height: 30, class: "rounded-circle" %>
                      </div>
                    <% end %>
                    <div class= "arrow">
                      <i class="fas fa-chevron-right"></i>
                      <%= link_to "Accept", accept_application_path(application), method: :patch, class: "green-color"%>
                    </div>
                  </div>
                  <p class="m-0 team-name-ngo"><%= application.team.name %></p>
                </div>
              </div>
            </div>
          </div>

          <div class="application-status mr-2">
            <% if application.status == "pending" %>
              <div class="accept-button px-3 my-2">
                <%= link_to "Accept", accept_application_path(application), method: :patch, class: "green-color"%>
              </div>
              <div class="reject-button px-3 my-2">
                <%= link_to "Reject", reject_application_path(application), method: :patch, class: "red-color"%>
              </div>
            <% elsif application.status == "accepted" %>
              <p id="accepted-text">Accepted</p>
            <% elsif application.status == "rejected" %>
              <p style="font-size: 18px">Declined</p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/projects.html.erb
<!-- Mobile version -->
<div class="mobile-projects-index">
  <div class="has-navbar-so-margin">
    <%= render 'shared/mobile_navbar' %>
    <div class = "content-container">
      <div class="mobile-card-container my-3">
        <h2 style="font-weight:normal;font-size:28px;" class="title-mobile"> <%= t(".your_projects") %> </h2>
        <% @ngo_projects.each do |project| %>
          <%= link_to project_path(project) do %>
            <div class="mobile-project-card my-4">

              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <% project.photos.each_with_index do |photo, index| %>
                    <% if index == 0 %>
                      <li data-target="#carouselExampleIndicators" data-slide-to="<% index %>" class="active"></li>
                    <% else %>
                      <li data-target="#carouselExampleIndicators" data-slide-to="<% index %>"></li>
                    <% end %>
                  <% end %>
                </ol>
                <div class="carousel-inner">
                  <% project.photos.each_with_index do |photo, index| %>
                    <% if index == 0 %>
                      <div class="carousel-item active">
                        <%= cl_image_tag photo.key, class: "d-block project-image", alt:"Project picture" %>
                        <%= render "projects/partial_card_icons", project: project %>
                      </div>
                    <% else %>
                      <div class="carousel-item">
                        <%= cl_image_tag photo.key, class: "d-block project-image", alt:"Project picture" %>
                        <%= render "projects/partial_card_icons", project: project %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
              <div class="project-text-stuff ml-2">
                <h5 class="mt-2"><%= link_to project.title, project_path(project), class: "project-title"%></h5>
                <p class="project-ong"><%= project.ngo.name if project.ngo %></p>

                <% spots_taken_count = 0 %>
                <% project.applications.each do |application| %>
                      <% application_status = application.status %>
                      <% if application_status == "accepted" %>
                        <% team_id = application.team_id %>
                        <% team = Team.find(team_id) %>
                        <% total_members = team.team_memberships.count %>
                        <% total_members %>
                        <% spots_taken_count += total_members %>
                      <% end %>
                <% end %>
                <% spots_left = project.capacity - spots_taken_count %>
                <% spots_left %>

                <div class="project-elements d-flex justify-content-left">
                  <div class="element"><i class="far fa-clock"></i><%= project.start_date.strftime("%d %B") %></div>
                  <% if spots_left > 0 %>
                    <div class="element"><i class="fas fa-user-friends"></i><%= spots_left%> spots</div>
                  <% else %>
                    <div class="element"><i class="fas fa-user-friends"></i> Full</div>
                  <% end %>
                  <div class="element"><i class="fas fa-map-marker-alt"></i> <span class="location-to-replace" data-latitude="<%= project.latitude %>" data-longitude="<%= project.longitude %>">calculating...</span></div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>

        <!-- Create your team button -->
        <%= link_to t(".create_project_button"), new_project_path, class: "button-vamos primary-style w-100 mt-3 px-3" %>

      </div>
    </div>
  </div>
</div>
<!-- desktop version -->
<div class="has-navbar-so-margin">
<%= render 'shared/mobile_navbar' %>
<div class="desktop-projects-index">
  <div class="desktop-card-container">
    <div class="row">
      <div class="col-8">
        <div class="project-lists">
          <% @ngo_projects.each do |project| %>
          <%= link_to project_path(project) do %>
            <div class="row mx-3 py-4 border-top">
              <div class = "desktop-project-card">
                <div>
                  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <% project.photos.each_with_index do |photo, index| %>
                        <% if index == 0 %>
                          <li data-target="#carouselExampleIndicators" data-slide-to="<% index %>" class="active"></li>
                        <% else %>
                          <li data-target="#carouselExampleIndicators" data-slide-to="<% index %>"></li>
                        <% end %>
                      <% end %>
                    </ol>
                    <div class="carousel-inner">
                      <% project.photos.each_with_index do |photo, index| %>
                        <% if index == 0 %>
                          <div class="carousel-item active">
                            <%= cl_image_tag photo.key, class: "d-block project-image", alt:"Project picture" %>
                          </div>
                        <% else %>
                          <div class="carousel-item">
                            <%= cl_image_tag photo.key, class: "d-block project-image", alt:"Project picture" %>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
                </div>
                <div class="project-text-stuff ml-3">
                  <h5><%= link_to project.title, project_path(project), class: "project-title"%></h5>
                  <p class="project-ong my-2"><%= project.ngo.name if project.ngo %></p>

                  <% spots_taken_count = 0 %>
                  <% project.applications.each do |application| %>
                    <% application_status = application.status %>
                    <% if application_status == "accepted" %>
                      <% team_id = application.team_id %>
                      <% team = Team.find(team_id) %>
                      <% total_members = team.team_memberships.count %>
                      <% total_members %>
                      <% spots_taken_count += total_members %>
                    <% end %>
                  <% end %>
                  <% spots_left = project.capacity - spots_taken_count %>
                  <% spots_left %>
                  
                  <div class="project-elements d-flex">
                    <div class="element mr-3"><i class="far fa-clock"></i><%= project.start_date.strftime("%d %B") %></div>
                    <div class="element mr-3"><i class="fas fa-user-friends"></i>
                      <% if spots_left < 0 %>
                        <%= %> Full
                      <% elsif spots_left == 1 %>
                        <%= spots_left%> spot left
                      <% else %>
                        <%= spots_left%> spots left
                      <% end %>
                    </div>
                    <div class="element"><i class="fas fa-map-marker-alt"></i> <span class="location-to-replace" data-latitude="<%= project.latitude %>" data-longitude="<%= project.longitude %>">calculating...</span></div>
                  </div>
                  <div class="project-description mt-4">
                    <p class="paragraph-no-margin"><%= project.description %></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>

        <!-- Create your team button -->
        <%= link_to t(".create_project_button"), new_project_path, class: "button-vamos primary-style mt-3 mb-5", id: "button-info-desktop" %>

      </div>
      <div class="col-4">
        <div class="image-container">
          <%= image_tag "volunteer_img_ngo.jpg", class: "filter-image"%>
        </div>
      </div>
    </div>
  </div>
</div>
</div>