config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope "(:locale)", locale: /es|de/ do

    resources :projects, only: [:index, :create, :new, :show] do
      resources :applications, only: [:new, :create]
    end

    get 'applications/:application_id/confirmation', to: 'applications#confirmation', as: :application_confirmation

    root to: 'pages#home'
    get 'ngos/home', to: 'ngos#home', as: :ngos_home
    get 'about-vamos', to: 'pages#about_vamos', as: :about_vamos
    get 'location', to: 'pages#filter_location', as: :filter_location
    get 'interests', to: 'pages#filter_interests', as: :filter_interests
    get 'timeframe', to: 'pages#filter_timeframe', as: :filter_timeframe
    get "dashboard", to: "users#dashboard", as: :user_dashboard
    get 'time', to: 'pages#filter_time', as: :filter_time
    get 'users/profile', to: 'users#profile', as: :user_profile
    get 'privacy-policy-vamos', to: 'pages#privacy_policy_vamos', as: :privacy_policy_vamos

    resources :conversations, only: [:index, :show, :create] do
      resources :messages, only: [:create]
    end

    get 'sitemap', to: 'sitemap#index', defaults: { format: "xml" }

    resources :teams, only: [:new, :create]

    get 'users/projects', to: 'users#projects', as: :user_projects #last modification

    resources :ngos, only: [:new, :create]

    resources :applications, only: [:index, :show] do
      resources :reviews, only: [:new, :create]
    end

    resources :applications, only: [] do
      member do
        patch "/accept_applications", to: "applications#accept_applications", as: :accept_applications
        patch "/reject_applications", to: "applications#reject_applications", as: :reject_applications
        patch "/accept_conversation", to: "applications#accept_conversation", as: :accept_conversation
        patch "/reject_conversation", to: "applications#reject_conversation", as: :reject_conversation
      end
    end

  end













  # needed for modal login

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_desktop_footer.html.erb
<div class="desktop-footer">
  <div class="d-flex justify-content-around align-items-center">
    <div class="footer-icons">
      <a class="footer-link" href="#"><i class="fab fa-instagram pl-2"></i></a>
      <a class="footer-link" href="https://www.facebook.com/VamosVolunteering"><i class="fab fa-facebook pl-2"></i></a>
      <a class="footer-link" href="https://www.linkedin.com/company/vamos-volunteering"><i class="fab fa-linkedin pl-2"></i></a>
    </div>

    <div>
      <p class="paragraph-no-margin white"> <%= link_to t("global.navbar.about"), about_vamos_path, class: "footer-link" %></p>
      <p class="paragraph-no-margin white"> <%= link_to t("global.navbar.privacy_policy"), privacy_policy_vamos_path, class: "footer-link" %></p>
    </div>

    <div class="footer-contact white">
      <p class="paragraph-no-margin white">Barcelona, Vienna, Paris</p>
      <p class="paragraph-no-margin white">info@vamosbarcelona.com</p>
      <p class="paragraph-no-margin white"> © 2020 Vamos! Global</p>
    </div>

  </div>
</div>

app/views/shared/_desktop_navbar.html.erb
<nav class="desktop-navbar navbar navbar-expand-sm navbar-light">
  <div>
    <%= link_to root_path, class: "navbar-brand ml-3" do %>
      <%= image_tag "final_logo.png", alt: "Logo of Vamos Barcelona, orange V and black amos", style: "width: 150px"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav navbar-right">

        <% if user_signed_in? %>

          <% if current_user.ngo %>

            <li id="user-view" class="yes-signed nav-item mr-2 <%= 'active' if current_page?(controller: '/projects', action: 'index') %>">
              <%= link_to t("global.navbar.user_view"), projects_path, class: "nav-link" %>
              <%# By using links, we ensure that default_url_options are actually used!  %>
            </li>

            <li id="applications" class="yes-signed nav-item mr-2 <%= 'active' if current_page?(controller: '/applications', action: 'index') %>">
              <%= link_to t("global.navbar.applications"), applications_path, class: "nav-link" %>
            </li>

          <% else %>

            <li id="search-projects" class="yes-signed nav-item mr-2 <%= 'active' if current_page?(controller: '/projects', action: 'index') %>">
              <%= link_to t("global.navbar.search"), projects_path, class: "nav-link" %>
              <%# By using links, we ensure that default_url_options are actually used!  %>
            </li>

            <li id="dashboard" class="yes-signed nav-item mr-2 <%= 'active' if current_page?(controller: '/users', action: 'profile') %>">
              <%= link_to t("global.navbar.dashboard"), user_profile_path, class: "nav-link" %>
            </li>

          <% end %>

          <li id="messages" class="yes-signed nav-item mr-2 <%= 'active' if current_page?(controller: '/conversations', action: 'index') %>">
            <%= link_to t("global.navbar.conversations"), conversations_path, class: "nav-link" %>
          </li>

          <li id="logedin" class="yes-signed nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% facebook_avatar_url = current_user.facebook_picture_url %>
              <% if facebook_avatar_url %>
                <%= image_tag facebook_avatar_url, width: 50, height: 50, class: "avatar-middle"%>
              <% elsif %>
                <%= cl_image_tag current_user.photo.key, width: 50, height: 50, class: "avatar-middle" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <% if current_user.ngo %>
                <%= link_to t("global.navbar.profile"), user_profile_path, class: "dropdown-item" %>
                <%= link_to t("global.navbar.my_projects"), user_projects_path, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to t("global.navbar.logout"), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
          <%= render 'shared/language_change' %>
        <% else %>
          <li id="search-projects" class="no-signed nav-item mr-2 <%= 'active' if current_page?(controller: '/projects', action: 'index') %>">
            <%= link_to t("global.navbar.search"), projects_path, class: "nav-link" %>
            <%# By using links, we ensure that default_url_options are actually used!  %>
          </li>
          <li id="find-volunteers" class="no-signed nav-item <%= 'active' if current_page?(controller: '/ngos', action: 'home') %>">
            <%= link_to t("global.navbar.find"), ngos_home_path, class: "nav-link" %>
          </li>
          <li id="about-vamos" class="no-signed nav-item mr-2 <%= 'active' if current_page?(controller: '/pages', action: 'about_vamos') %>">
            <%= link_to t("global.navbar.about"), about_vamos_path, class: "nav-link" %>
          </li>
          <li id="login" class="no-signed nav-item mr-3">
            <%= link_to t("global.navbar.login"), "", data: {toggle: "modal", target: ".bd-example-modal-lg"}, class: "nav-link" %>
          </li>
          <%= render 'shared/language_change' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<%= render 'shared/login_form' %>

app/views/shared/_flashes.html.erb
<div class="alert-test">
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
</div>

app/views/shared/_language_change.html.erb
<li class= "ml-2">
  <%= link_to "/" do %>
    <div class="d-flex align-items-center">
      <%= image_tag "Flags/flag_uk.jpg", alt: "Flag of UK to change language to English", class: "flags mb-2"%>
    </div>
  <% end %>

  <%= link_to root_path(locale: :es) do %>
    <div class="d-flex align-items-center">
      <%= image_tag "Flags/flag_spain.jpg", alt: "Flag of Spain to change language to Spanish", class: "flags"%>
    </div>
  <% end %>
</li>

app/views/shared/_languages_bottom_left.html.erb
<div class="language-bottom-left hide-desktop d-flex py-2 pl-3">

  <%= link_to "/" do %>
    <div class="d-flex align-items-center mr-4">
      <%= image_tag "Flags/flag_uk.jpg", alt: "Flag of UK to change language to English", class: "flags mb-2 hide-desktop"%>
    </div>
  <% end %>

  <%= link_to root_path(locale: :es) do %>
    <div class="d-flex align-items-center">
      <%= image_tag "Flags/flag_spain.jpg", alt: "Flag of Spain to change language to Spanish", class: "flags hide-desktop"%>
    </div>
  <% end %>
</div>

app/views/shared/_login_form.erb
<div class="modal fade bd-example-modal-lg"tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t("global.modal.login")%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="errors ml-3 mt-3">
      </div>

      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), remote:true) do |f| %>
          <div class="form-inputs">
            <%= f.input :email,
                required: false,
                autofocus: true,
                label:false,
                placeholder: "Email",
                input_html: { class: "mb-4", autocomplete: "email" } %>
            <%= f.input :password,
                required: false,
                label: false,
                placeholder: t("global.modal.password"),
                input_html: { class: "mb-4",autocomplete: "current-password" } %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class="button-modal modal-footer">
            <%= f.button :submit, t("global.modal.login_button"), class: "button-vamos primary-style my-3 w-100" %>
          </div>
        <% end %>
        <div class="my-4">
        <%= render "devise/shared/links" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_logo_top_left.html.erb
<div class="logo-top-left">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "final_logo.png", alt: "Logo of Vamos Barcelona, orange V and black amos.", style: "width: 170px;" %>
  <% end %>
</div>

app/views/shared/_logo_top_right.html.erb
<div class="logo-top-right hide-desktop">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "final_logo.png", alt: "Logo of Vamos Barcelona, orange V and black amos." style: "width: 150px" %>
  <% end %>
</div>

app/views/shared/_mobile_navbar.html.erb
<div class="mobile-navbar d-flex justify-content-around align-items-center">

  <% if user_signed_in? && current_user.ngo %>

    <div class="nav-element <%= "active" if current_page?(user_profile_path) %>">
      <%= link_to user_profile_path do %>
        <div>
          <i class="far fa-user nav-icon"></i>
          <p class="nav-icon-tag"><%= t("global.navbar.profile") %></p>
        </div>
      <% end %>
    </div>

    <div class="nav-element <%= "active" if current_page?(applications_path) %>">
      <%= link_to applications_path do %>
        <div>
          <i class="far fa-check-square nav-icon"></i>
          <p class="nav-icon-tag"><%= t("global.navbar.applications") %></p>
        </div>
      <% end %>
    </div>

    <div class="nav-element <%= "active" if current_page?(user_projects_path) %>">
      <%= link_to user_projects_path do %>
        <div>
          <i class="fas fa-list nav-icon"></i>
          <p class="nav-icon-tag"><%= t("global.navbar.my_projects") %></p>
        </div>
      <% end %>
    </div>

    <div class="nav-element <%= "active" if current_page?(conversations_path) %>">
      <%= link_to conversations_path do %>
        <div>
          <i class="far fa-comment-alt nav-icon"></i>
          <p class="nav-icon-tag"><%= t("global.navbar.messages") %></p>
        </div>
      <% end %>
    </div>

  <% elsif user_signed_in?%>

    <div class="nav-element <%= "active" if current_page?(controller: "projects", action: "index") %>">
      <%= link_to projects_path do %>
        <div>
          <i class="fas fa-list nav-icon"></i>
          <p class="nav-icon-tag"><%= t("global.navbar.explore") %></p>
        </div>
      <% end %>
    </div>
    <div class="nav-element <%= "active" if current_page?(user_profile_path) %>">
      <%= link_to user_profile_path do %>
        <div>
          <i class="far fa-user nav-icon"></i>
          <p class="nav-icon-tag"><%= t("global.navbar.profile") %></p>
        </div>
      <% end %>
    </div>
    <div class="nav-element <%= "active" if current_page?(conversations_path) %>">
      <%= link_to conversations_path do %>
        <div>
          <i class="far fa-comment-alt nav-icon"></i>
          <p class="nav-icon-tag"><%= t("global.navbar.conversations") %></p>
        </div>
      <% end %>
    </div>

  <% else %>

    <div class="nav-logo">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "final_logo.png", alt: "Logo of Vamos Barcelona, orange V and black amos", style: "width: 130px" %>
      <% end %>
    </div>
    <div class="nav-element">
      <%= link_to t("global.navbar.login"), data: {toggle: "modal", target: ".bd-example-modal-lg"}, class: "nav-link mb-2" do %>
        <div>
          <i class="far fa-user nav-icon"></i>
          <p class="nav-icon-tag">SIGN IN</p>
        </div>
      <% end %>
    </div>

  <% end %>
</div>

<%= render 'shared/login_form' %>

app/views/shared/_navbar.html.erb
<div class="navbar-container d-flex justify-content-around align-items-center">

  <% if user_signed_in? %>

    <div class="nav-element <%= "active" if current_page?(controller: "projects", action: "index") %>">
      <%= link_to "/projects" do %>
        <div>
          <i class="fas fa-list nav-icon"></i>
          <p class="nav-icon-tag">EXPLORE</p>
        </div>
      <% end %>
    </div>
    <div class="nav-element <%= "active" if current_page?(user_profile_path(current_user)) %>">
      <%= link_to user_profile_path(current_user) do %>
        <div>
          <i class="far fa-user nav-icon"></i>
          <p class="nav-icon-tag">PROFILE</p>
        </div>
      <% end %>
    </div>
    <div class="nav-element <%= "active" if current_page?(conversations_path) %>">
      <%= link_to conversations_path do %>
        <div>
          <i class="far fa-comment-alt nav-icon"></i>
          <p class="nav-icon-tag">MESSAGES</p>
        </div>
      <% end %>
    </div>

  <% else %>

    <div class="nav-logo">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "Vamos_logo_final.png"%>
      <% end %>
    </div>
    <div class="nav-element">
      <%= link_to "/users/sign_in" do %>
        <div>
          <i class="far fa-user nav-icon"></i>
          <p class="nav-icon-tag">SIGN IN</p>
        </div>
      <% end %>
    </div>

  <% end %>
</div>