config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope "(:locale)", locale: /es|de/ do

    resources :projects, only: [:index, :create, :new, :show] do
      resources :applications, only: [:new, :create]
    end

    get 'applications/:application_id/confirmation', to: 'applications#confirmation', as: :application_confirmation

    root to: 'pages#home'
    get 'ngos/home', to: 'ngos#home', as: :ngos_home
    get 'about-vamos', to: 'pages#about_vamos', as: :about_vamos
    get 'location', to: 'pages#filter_location', as: :filter_location
    get 'interests', to: 'pages#filter_interests', as: :filter_interests
    get 'timeframe', to: 'pages#filter_timeframe', as: :filter_timeframe
    get "dashboard", to: "users#dashboard", as: :user_dashboard
    get 'time', to: 'pages#filter_time', as: :filter_time
    get 'users/profile', to: 'users#profile', as: :user_profile
    get 'privacy-policy-vamos', to: 'pages#privacy_policy_vamos', as: :privacy_policy_vamos

    resources :conversations, only: [:index, :show, :create] do
      resources :messages, only: [:create]
    end

    get 'sitemap', to: 'sitemap#index', defaults: { format: "xml" }

    resources :teams, only: [:new, :create]

    get 'users/projects', to: 'users#projects', as: :user_projects #last modification

    resources :ngos, only: [:new, :create]

    resources :applications, only: [:index, :show] do
      resources :reviews, only: [:new, :create]
    end

    resources :applications, only: [] do
      member do
        patch "/accept_applications", to: "applications#accept_applications", as: :accept_applications
        patch "/reject_applications", to: "applications#reject_applications", as: :reject_applications
        patch "/accept_conversation", to: "applications#accept_conversation", as: :accept_conversation
        patch "/reject_conversation", to: "applications#reject_conversation", as: :reject_conversation
      end
    end

  end













  # needed for modal login

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :ngo
  has_many :applications
  has_many :reviews, through: :applications
  has_many_attached :photos
  validates :photos, presence: true
  validates :title, length: { maximum: 40 }, presence: true
  validates :start_date, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :capacity, presence: true
  validates :category, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def spots_left
    spots_taken = 0

    self.applications.each do |application|
      if application.status == "accepted"
        team = Team.find(application.team_id)
        total_members = team.team_memberships.count
        spots_taken += total_members
      end
    end

    return self.capacity - spots_taken
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @projects = Project.all

    filter_projects

    @markers = @projects.map do |project|
      {
        lat: project.latitude,
        lng: project.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { project: project })
      }
    end
  end

  def show
    @project = Project.find(params[:id])
    @ngo = @project.ngo.name
    @reviews = @project.reviews

      @markers = [{
      lat: @project.latitude,
      lng: @project.longitude
    }]
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @ngo = current_user.ngo
    @project.ngo = @ngo
    if @project.save
      redirect_to user_projects_path
    else
      render :new
    end
  end

  private

  def filter_projects
    @projects = @projects.near(params[:address], 50) unless params[:address].blank?

    categories_params = params[:categories].split() if params[:categories].present?

    @projects = @projects.where('category IN (?)', categories_params) unless categories_params&.reject(&:blank?).blank?

    @projects = @projects.where('timeframe IN (?)', params[:timeframe]) unless params[:timeframe]&.reject(&:blank?).blank?

  end

  def project_params
    params.require(:project).permit(:title, :address, :description, :capacity, :category, :timeframe, :start_time, :end_time, :start_date, :end_date, photos:[])
  end

end

app/views/projects/_info_window.html.erb
<div class="info-window">
  <%= link_to project_path(project) do %>
  <div class="project-image">
    <% if project.photos.attached? %>
      <%= cl_image_tag project.photos.first.key%>
    <% end %>
  </div>

  <div class="project-text-stuff ml-2">
    <h3 class="mt-2 mb-1"><%= link_to project.title, project_path(project), class: "project-title"%></h3>
    <p class="project-ong mb-3"><%= project.ngo.name if project.ngo %></p>
    <div class="project-elements d-flex justify-content-left">
      <div class="element"><i class="far fa-clock"></i><%= l(project.start_date, format: :short) %></div>
      <%=  %>

      <% if project.capacity < 1 %>
      <div class="element mr-3"><i class="fas fa-user-friends"></i> <%= t(".spots_zero") %></div>
      <% elsif project.capacity < 6 %>
      <div class="element mr-3"><i class="fas fa-user-friends"></i> <%= t(".spots_low", name: project.capacity) %></div>
      <% else %>
      <div class="element mr-3"><i class="fas fa-user-friends"></i> <%= t(".spots_high", name: project.capacity) %> </div>
      <% end %>

      <div class="element"><i class="fas fa-map-marker-alt"></i> <span class="location-to-replace" data-latitude="<%= project.latitude %>" data-longitude="<%= project.longitude %>">calc.</span></div>
    </div>
  </div>
  <% end %>
</div>

app/views/projects/_partial_card_icons.html.erb
 <div class="interest-icon border rounded-circle">
  <!-- <i class="fas fa-leaf"></i> -->
  <% if project.category == "Children" || project.category == "Niños"  %>
  <i class="icon fas fa-child"></i>
  <% elsif project.category == "Social" %>
  <i class="icon fas fa-user-friends mr-0"></i>
  <% elsif project.category == "Cultural" %>
  <i class="icon fas fa-music"></i>
  <% elsif project.category == "Climate" || project.category == "Medio Ambiente" %>
  <i class="icon fas fa-leaf"></i>
  <% elsif project.category == "Medical" || project.category == "Salud"%>
  <i class="fas fa-briefcase-medical"></i>
  <% else project.category == "Seniors" || project.category == "Mayores"%>
  <i class="icon fab fa-accessible-icon"></i>
  <% end %>
</div>

app/views/projects/_partial_filter_boxes_interest.html.erb
 <div class="onboarding-buttons buttons filter-buttons">
  <% categories = {
    t("global.interests.children") => "fas fa-child",
    t("global.interests.social") => "fas fa-user-friends mr-0",
    t("global.interests.cultural") => "fas fa-music",
    t("global.interests.climate") => "fas fa-leaf",
    t("global.interests.medical") => "fas fa-briefcase-medical",
    t("global.interests.seniors") => "fab fa-accessible-icon",
    } %>
  <% categories.each do |category, logo| %>
  <input type="checkbox" class="hidden category-input" value="<%= category %>" name="categories[]" id="categories_<%= category %>" <%= "checked" if params[:categories]&.include?(category) %> >
  <label class="category-button button <%= "active" if params[:categories]&.include?(category) %>" for="categories_<%= category %>">
    <div class="width-small-interest text-center">
      <div class="interest-icon">
        <i class="<%= logo %>"></i>
      </div>
      <%= category%>
    </div>
  </label>

  <% end %>
</div>

app/views/projects/_partial_filter_boxes_time.htlm.erb
<div class="buttons d-flex justify-content-between flex-wrap">
  <% ["1 - 4", "5 - 9", "10+"].each do |time| %>
  <input type="checkbox" class="hidden time-input" value="<%= time %>" name="time[]" id="time_<%= time %>">
  <label class="time-button button <%= "active" if params[:time]&.include?(time) %>" for="time_<%= time %>">
    <%= time %>
  </label>
  <% end %>
</div>

app/views/projects/_partial_filter_boxes_time.html.erb
<div class="buttons filter-buttons">
  <% ["1 - 4 h/week", "5 - 9 h/week", "10+ h/week"].each do |time| %>
  <input type="checkbox" class="hidden time-input" value="<%= time %>" name="time[]" id="time_<%= time %>" <%= "checked" if params[:time]&.include?(time) %>>
  <label class="time-button button <%= "active" if params[:time]&.include?(time) %>" for="time_<%= time %>">
    <%= time %>
  </label>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="content-container-photo">
<!--   Desktop version -->
  <div class= "desktop-view-create-project hide-mobile">
    <div class= "banner-home-page" style="background-image: url('<%= image_path "NGO_Project/create-project1.jpg"%>')">
      <div class= "card-category-ngo-new">

    <!-- form start -->
        <div class="form-group">

          <h2 class="mb-4"><%= t(".create") %> <span style="color: #fb8500"><%= t(".your") %> </span></h2>
          <p><%= t(".subheading") %> </p>
      <!-- Form -->

          <%= simple_form_for @project do |f|  %>
          <% if @project.errors.any? %>
          <div class="errors-container">
            <ul>
              <% @project.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
         <% end %>
            <%= f.input :title, placeholder: t(".project_name"), label:false, class: 'form-control-project' %>
            <%= f.input :description, placeholder: t(".description"), label:false,class: 'form-control-project' %>
            <%= f.input :address, placeholder: t(".address"), label:false,class: 'form-control-project' %>
            <%= f.input :category, collection: t(".categories"), label:t(".category"), class: 'form-control' %>
            <div class="d-flex align-items-end justify-content-between">
              <%= f.input :capacity, collection: 1..30, label: t(".how_many"),class: 'form-control' %>
              <%= f.input :start_date, label: t(".start"),class: 'form-control' %>
            </div>


          <div class="d-flex align-items-center">
            <label class="button-upload-file mr-2">
            <%= t(".pictures") %>
            <span style="display:none;">
            <%= f.input :photos, as: :file, input_html: { multiple: true, class: "logo-input"} %>
            </span>
            </label>
            <div class="logo-file-name">
            </div>
          </div>
          <div class="d-flex justify-content-between">
            <div id="back">
              <%= link_to t(".back"),user_profile_path, class: "orange mt-10"%>
            </div>
            <%= f.submit t(".create") , class: "button-vamos primary-style w-50 mt-3 ml-10"%>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<!--   Mobile version -->
  <div class="hide-desktop">
  <!--   Back arrow to go to dashboard -->

    <div class="d-flex mb-2 align-items-center justify-content-right">
      <i class='fas fa-chevron-left orange'></i>
      <i class='fas fa-chevron-left orange mr-1'></i>
      <%= link_to "Back to dashboard",user_profile_path, class: "orange"%>
    </div>

    <!-- form start -->
    <div class="form-group">

        <h1 class="mb-4">Create your project</h1>

      <!-- Form -->

        <%= simple_form_for @project do |f|  %>
        <% if @project.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%= f.input :title, placeholder: t(".project_name"), label:false, class: 'form-control-project' %>
        <%= f.input :description, placeholder: t(".description"), label:false,class: 'form-control-project' %>
        <%= f.input :address, placeholder: t(".address"), label:false,class: 'form-control-project' %>
        <%= f.input :category, collection: t(".categories"), label:t(".category"), class: 'form-control' %>
        <%= f.input :capacity, collection: 1..30, label: t(".how_many"),class: 'form-control' %>
        <%= f.input :start_date, label: t(".start"),class: 'form-control' %>

        <div class="d-flex align-items-center">
          <label class="button-upload-file mr-2">
          <%= t(".pictures") %>
          <span style="display:none;">
          <%= f.input :photos, as: :file, input_html: { multiple: true, class: "logo-input"} %>
          </span>
          </label>
          <div class="logo-file-name">
          </div>
        </div>
        <%= f.submit t(".create"), class: "button-vamos primary-style w-100 mt-3"%>
        <% end %>

    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="desktop-content-container">
  <div>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <% @project.photos.each_with_index do |photo, index| %>
          <% if index == 0 %>
            <li data-target="#carouselExampleIndicators" data-slide-to="<% index %>" class="active"></li>
          <% else %>
            <li data-target="#carouselExampleIndicators" data-slide-to="<% index %>"></li>
          <% end %>
        <% end %>
      </ol>
      <div class="carousel-inner">
        <% @project.photos.each_with_index do |photo, index| %>
          <% if index == 0 %>
            <div class="carousel-item active">
              <%= cl_image_tag photo.key, class: "d-block project-image-show", alt:"Project picture" %>
            </div>
          <% else %>
            <div class="carousel-item">
              <%= cl_image_tag photo.key, class: "d-block project-image-show", alt:"Project picture" %>
            </div>
          <% end %>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

<!-- back button -->

<%= link_to projects_path do %>
<div class="go-back-arrow">
  <i class='fas fa-chevron-left hide-desktop'></i>
</div>
<% end %>

<!-- back button end -->

<div class="desktop-content-container content-container">

<!-- tabs -->
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="project-tab" data-toggle="tab" href="#project" role="tab" aria-controls="project" aria-selected="true"><h5 class="paragraph-no-margin orange-title"><%= t(".project") %> </h5></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="ngo-tab" data-toggle="tab" href="#ngo" role="tab" aria-controls="ngo" aria-selected="false"><h5 class="paragraph-no-margin orange-title"><%= t(".organization") %></h5></a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <!-- PROJECT INFO -->
    <div class="tab-pane fade show active" id="project" role="tabpanel" aria-labelledby="project-tab">
      <div class="mt-3" id="project-tab">
        <h2 class="h2-less-margin"><%= @project.title %></h2>
        <div class="mt-2">
          <p><%= @project.description %> </p>
        </div>

        <% spots_taken_count = 0 %>
          <% @project.applications.each do |application| %>
                <% application_status = application.status %>
                <% if application_status == "accepted" %>
                  <% team_id = application.team_id %>
                  <% team = Team.find(team_id) %>
                  <% total_members = team.team_memberships.count %>
                  <% total_members %>
                  <% spots_taken_count += total_members %>
                <% end %>
          <% end %>
        <% spots_left = @project.capacity - spots_taken_count %>
        <% spots_left %>


        <div class="elements-container d-flex mt-3">
          <div class="mr-3">
             <% if spots_left < 1 %>
            <div class="element"><i class="fas fa-user-friends"></i> <%= t(".spots_zero") %></div>
            <% elsif spots_left < 6 %>
            <div class="element"><i class="fas fa-user-friends"></i> <%= t(".spots_low", name: spots_left) %></div>
            <% else %>
            <div class="element"><i class="fas fa-user-friends"></i> <%= t(".spots_high", name: spots_left) %> </div>
            <% end %>

          </div>
          <div class="element mr-2"><i class="far fa-clock"></i>
          </div>
          <div class="mr-3">
            <p><%= l(@project.start_date, format: :short)%> </p>
          </div>
          <div class="element mr-2"><i class="fas fa-map-marker-alt"></i>
          </div>
          <div class="mr-3">
            <p>5km</p>
          </div>
        </div>

       <!-- Apply button -->

        <% if user_signed_in? %>
          <% if current_user.teams.any? %>
            <%= form_tag(new_project_application_path(@project), :method => "get") do %>
            <div class="desktop-apply-button-showpage apply-button-showpage">
            <%= submit_tag(t(".apply"), class: "button-vamos primary-style mb-5") %>
            </div>
            <% end %>
          <% else %>
            <%= form_tag(new_team_path, :method => "get") do %>
              <%= hidden_field_tag(:id, params["id"]) %>
              <div class="desktop-apply-button-showpage apply-button-showpage">
              <%= submit_tag(t(".apply"), class: "button-vamos primary-style mb-5") %>
              </div>
              <% end %>
          <% end %>

        <% else %>
            <%= form_tag(new_team_path, :method => "get") do %>
            <%= hidden_field_tag(:id, params["id"]) %>
            <div class="desktop-apply-button-showpage apply-button-showpage">
            <%= submit_tag(t(".apply"), class: "button-vamos primary-style mb-5") %>
            </div>
          <% end %>
        <% end %>


      <!-- Map -->

        <div class="mt-2"
        id="map"
        style="width: 100%;
        height: 40vh;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

      <!-- Reviews -->

        <div class="mt-4">
          <h2><%= t(".reviews_for", count: @reviews.count, name: @project.ngo.name) %> </h2>
        </div>
        <div class="reviews my-3 align-items-center">
          <% @reviews.each do |review| %>
            <div class = "each_review d-flex my-3 align-items-center">
              <% if review.user.photo.attached? %>
                <%= cl_image_tag review.user.photo.key , class: "avatar mr-2"%>
              <% end %>
              <div>
                <div class="div">
                  <p class="review-name m-0"><strong><%= review.user.first_name %></strong></p>
                  <p class="paragraph m-0"><%= review.content %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <!-- NGO INFO -->
    <div class="tab-pane fade mt-3" id="ngo" role="tabpanel" aria-labelledby="ngo-tab">
      <div class="info-all d-flex align-items-top">
        <div class="logo mr-3 mt-10">
          <% if @project.ngo.logo.attached? %>
          <%= cl_image_tag @project.ngo.logo.key, class: "avatar" %>
          <% end %>
        </div>
        <div class="name_tel">
          <div class= "name">
            <h2 class="h2-less-margin"><%= @project.ngo.name %></h2>
          </div>
          <div class="address d-flex mt-1 mb-3">
            <div class="element mr-2"><i class="fas fa-map-marker-alt"></i>
            </div>
            <div class="mr-3">
              <p class="paragraph-no-margin"><%= @project.ngo.address %> </p>
            </div>
          </div>
        </div>
      </div>
      <div class="border-bottom">
      </div>
      <div class="mt-2">
        <p><%= @project.ngo.description %> </p>
      </div>
      <div class = "user_ngo_info-container mb-2">
        <div class="border-bottom">
        </div>
        <div class= "user_info d-flex">
          <div class="user_ngo_photo mr-3 mt-3">
            <% if @project.ngo.user.photo.attached? %>
            <%= cl_image_tag @project.ngo.user.photo.key , class: "avatar"%>
            <% end %>
          </div>
          <div class= "all infos mt-3">
            <div class = "contact">
              <h5> <%= @project.ngo.user.first_name %> is your contact </h5>
            </div>
          </div>
        </div>

        <%= form_tag(new_team_path, :method => "get") do %>
          <%= hidden_field_tag(:id, params["id"]) %>
          <div class="desktop-apply-button-showpage apply-button-showpage">
          <%= submit_tag(t(".apply"), class: "button-vamos primary-style mb-5") %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

<div style="height: 80px">
</div>


<%= form_tag(new_team_path, :method => "get") do %>
  <%= hidden_field_tag(:id, params["id"]) %>
  <div class="mobile-apply-button-showpage apply-button-showpage">
  <%= submit_tag(t(".apply"), class: "button-vamos primary-style mb-5") %>
  </div>
<% end %>